[package]
name = "divvun-speech"
version = "0.3.0"
edition = "2024"

[lib]
crate-type = ["lib", "staticlib"]

[build-dependencies]
cmake = "0.1"

[dependencies]
libc = "0.2"
thiserror = "2"
serde_json = "1"
